### ISSUE TITLE
undefined method `rss_version' for nil:NilClass

### ISSUE THREAD

**Issue by farukca** [feedparser/feedparser#2]
FeedParser::Parser.parse('feeds.feedburner.com/GiantRobotsSmashingIntoOtherGiantRobots') 

in rails console; the sub command gets error; 
[debug] using stdlib rss/0.2.7
[debug] Parsing feed...
[debug]   feed.class=NilClass
NoMethodError: undefined method `rss_version' for nil:NilClass from /Users/farukcelik/.rvm/gems/ruby-2.1.0/gems/feedparser-1.0.0/lib/feedparser/builder/rss.rb:30:in`build_feed' from /Users/farukcelik/.rvm/gems/ruby-2.1.0/gems/feedparser-1.0.0/lib/feedparser/builder/rss.rb:19:in `initialize' from /Users/farukcelik/.rvm/gems/ruby-2.1.0/gems/feedparser-1.0.0/lib/feedparser/builder/rss.rb:14:in`new'    from /Users/farukcelik/.rvm/gems/ruby-2.1.0/gems/feedparser-1.0.0/lib/feedparser/builder/rss.rb:14:in `build' from /Users/farukcelik/.rvm/gems/ruby-2.1.0/gems/feedparser-1.0.0/lib/feedparser/parser.rb:37:in`parse' from /Users/farukcelik/.rvm/gems/ruby-2.1.0/gems/feedparser-1.0.0/lib/feedparser/parser.rb:12:in `parse'
    from (irb):35
    from /Users/farukcelik/.rvm/gems/ruby-2.1.0/gems/railties-4.1.7/lib/rails/commands/console.rb:90:in`start'
    from /Users/farukcelik/.rvm/gems/ruby-2.1.0/gems/railties-4.1.7/lib/rails/commands/console.rb:9:in `start'
    from /Users/farukcelik/.rvm/gems/ruby-2.1.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:69:in`console'
    from /Users/farukcelik/.rvm/gems/ruby-2.1.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
    from /Users/farukcelik/.rvm/gems/ruby-2.1.0/gems/railties-4.1.7/lib/rails/commands.rb:17:in`<top (required)>'
    from bin/rails:8:in `require'
    from bin/rails:8:in`<main>'

**Comment by geraldb** [comment]
Please send bugs to the mailing list (just found by accident). You must always include http:// in your url e.g. http://feeds.feedburner.com... Cheers.
