### ISSUE TITLE
It would be great to have author/authors of feed items

### ISSUE THREAD

**Issue by onli** [feedparser/feedparser#3]
If an atom feed entry has no author set, feedparser could fill in the author from the feed element.

**Comment by geraldb** [comment]
@onli  Good point.  The author/authors are missing. Need to get added if present. Cheers.

**Comment by geraldb** [comment]
@onli  FYI: Authors are now included in all feed formats (Atom, RSS, JSON) if present. See the new authors.rb struct/class. Please, update your feedparser gem to 1.2+. Cheers.

**Comment by onli** [comment]
Thanks!
