### ISSUE TITLE
Keep media enclosures

### ISSUE THREAD

**Issue by onli** [feedparser/feedparser#4]
Podcast feeds and RSS feeds in general can contain an enclosure element that enables players to show directly the sound file which can be played. Atom supports this as well, https://github.com/gpodder/podcast-feed-best-practice/blob/master/podcast-feed-best-practice.md#media-files-enclosures. But feedparser so far seems to strip that element. Is it possible to keep it, ideally to add it to the schema?

**Comment by geraldb** [comment]
@onli Good point. Yes, attachments / enclosures are still missing in the model. Needs to get added. Cheers.

**Comment by onli** [comment]
(Just to have the reference here, didn't realize I'd have to add it to the body of the PR) I sent a PR adding that, https://github.com/feedparser/feedparser/pull/5

**Comment by geraldb** [comment]
Great.  Thanks for the kick off. Merged your changes / additions. Keep it up.  Cheers.

**Comment by onli** [comment]
Hi @geraldb. I wanted to ask whether we could get a gem release with that feature enabled?

**Comment by geraldb** [comment]
@onli Thanks for the reminder. Will try to push out a new release later this week. Cheers.

**Comment by onli** [comment]
Great, thanks :)

**Comment by geraldb** [comment]
@onli  Thanks for getting it started. Added a new struct for attachments (with an alias for enclosures) and pushed out a new version, that is, 2.1.0. Keep it up. Cheers. Prost.

**Comment by onli** [comment]
Thanks for packing this into an update. It seems to work just fine :)

I just realized that one of the feeds this was requested for is from Youtube, and Youtube does not use simple enclosures. They use the Yahoo media namespace. http://bjohas.de/wiki/Enclosures_in_yahoo_media,_rss,_and_atom describes it, [this](https://www.youtube.com/feeds/videos.xml?playlist_id=PLJ-XLeHjvOas-TWpUUwAQ9VLixzHoO2YE) is a live example with a slightly different syntax.

Do you see a proper way how this could be supported as well, or is this just too far off from a regular feed? I have to admit not even seeing a way how the ruby rss parser and builder could access or create such elements.

**Comment by geraldb** [comment]
@onli  Good point.  Thanks for the detailed info about the media extension. I'd say looks like an attachment / enclosure with more attributes (if I'm not missing something), thus, I would add it to the attachments / enclosures array plus add some more (optional) attributes if missing.

As you said shouldn't be too hard if the ruby rss parses the element (way more difficult if the information is not accessible) - than the option is to extend the (standard) rss parser or use just a "vanilla" xml parser.  I'd say the first step is to check if you can access the media elements in rss2?
