### ISSUE TITLE
HTTPError 307

### ISSUE THREAD

**Issue by GeoHolz** [feedparser/feedparser#7]
I don't understand why... 
>>> d = feedparser.parse('https://www2.yggtorrent.gg/rss?action=generate&type=cat&id=2145')
>>> d
{'bozo': 1, 'entries': [], 'feed': {}, 'bozo_exception': <HTTPError 307: 'The HTTP server returned a redirect error that would lead to an infinite loop.\nThe last 30x error message was:\nTemporary Redirect'>}

**Comment by geraldb** [comment]
feedparser.parse does NOT fetch the feed (from the intertubes) it will ONLY parse the text.  You have to fetch the feed text first with your HTTP library of choice. Cheers. Prost.

**Comment by onli** [comment]
The error message is very strange for that though.

**Comment by geraldb** [comment]
FYI: Double checking your error - you are using the PYTHON feedparser library - this library here is about RUBY.
